### ISSUE TITLE
Inline media queries

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/ccss-compiler#1]
More **Concise** media queries:

```scss
.myResponsiveElement {
  width: 12em;
  width: 100% < 450px;
  width: 6em > 960px;
  font-size: 1.5rem > height: 800px;
}
```

Would produce:

```scss
.myResponsiveElement {
  width: 12em;
}

@media (max-width: 450px) {
  .myResponsiveElement {
    width: 100%;
  }
}

@media (min-width: 960px) {
  .myResponsiveElement {
    width: 6em;
  }
}

@media (min-height: 800px) {
  .myResponsiveElement {
    font-size: 1.5rem;
  }
}
```
