### ISSUE TITLE
Property lookup

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/ccss-compiler#2]
Example:

```scss
.element1 {
  margin-bottom: .element2[width];
}

.element2 {
  margin-top: 500px;
}
```

```scss
.selector {
  width: 100px;
  height: &[width];
}
```

Would produce:

```scss
.element1 {
  margin-bottom: 500px;
}

.element2 {
  margin-top: 500px;
}
```

```scss
.selector {
  width: 100px;
  height: 100px;
}
```

Also this *might* fix the issue with z-indexes:

```scss
.top {
  z-index: .bottom[z-index] + 1;
}

.bottom {
  z-index: 1;
}
```

Producing:

```scss
.top {
  z-index: 2;
}

.bottom {
  z-index: 1;
}
```
