### ISSUE TITLE
Unit: lh

### ISSUE THREAD

**Issue by jameskolce** [ConciseCSS/ccss-compiler#3]
The `lh` is an equivalent to the line-height of the root element.

```css
:root {
  font: 16px / 1.5 "Helvetica", "Arial", sans-serif;
}

section {
  margin-bottom: 1lh;
  padding-top: .5lh;
}
```

Would produce:

```css
:root {
  font: 16px / 1.5 "Helvetica", "Arial", sans-serif;
}

section {
  margin-bottom: 1.5rem;
  padding-top: 0.75rem;
}
```
